name: WCH_V307_RISC-V
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  target-gcc-riscv32-unknown-elf:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: update-tools
        run: |
          wget --no-check-certificate https://buildbot.embecosm.com/job/riscv32-gcc-ubuntu2204-release/10/artifact/riscv32-embecosm-ubuntu2204-gcc13.2.0.tar.gz
          tar -xzf riscv32-embecosm-ubuntu2204-gcc13.2.0.tar.gz -C ${{ runner.workspace }}
        working-directory: ./
      - name: target-riscv32-unknown-elf
        run: |
          PATH="${{ runner.workspace }}/riscv32-embecosm-ubuntu2204-gcc13.2.0/bin:$PATH"
          echo 'query compiler version'
          riscv32-unknown-elf-g++ -v
          bash ./Rebuild.sh
          ls -la ../Output/BareMetal_WCH_V307_RISC-V.hex
        working-directory: ./Build
